### ISSUE TITLE
AZO HAOPP BIFISIC infrastructure is not available online!

### ISSUE THREAD

**Issue by klimeto** [HRSEVESOSK/cide-ionic-app#67]
From Saturday 5.1.2020 the AZO HAOP VPN neither VIrtual machine 'pproo.azo.hr' and thus web apps of BIFISIC and CIDE are not longer available from Internet:

https://pproo.azo.hr/

https://pproo.azo.hr/bifisic

https://pproo.azo.hr/cide/app/

Please as Tome to check and fix the issue, so I can deploy the new developments I made to fix your issues!

Thank you.

**Comment by klimeto** [comment]
Infrastructure is available again.

**Comment by mzanoskihren** [comment]
Dear Tomaž and Martin, thank you for the information.
During mentioned period the servers were shut down.
After that they were switched on again. However, something seems to have happened which is why the data on Seveso plants are no longer being retrieved from REDS/RRMA (database on Seveso establishments) in BIFISIC. Also, data from other services are not retrieved.
Can you please check that and fix it?
Thanks in advance.
Best regards, Marijana Zanoški Hren

**Comment by mzanoskihren** [comment]
Dear Tomaž and Martin, thank you for the information (see picture 1. below).

During mentioned period the servers were shut down.
After that they were switched on again. However, something seems to have happened which is why the data on Seveso plants are no longer being retrieved from REDS/RRMA (database on Seveso establishments) in BIFISIC. Also, data from other services are not retrieved.
Can you please check that and fix it?

Thanks in advance.

Best regards, Marijana Zanoški Hren


Picture 1.
[cid:image001.png@01D5CABB.93AAFF50]


[cid:image001.jpg@01D5C4B0.4F6BCA10]




Zavod za zaštitu okoliša i prirode │Institute for Environment and Nature
Sektor za okoliš │Environmental sector

dr.sc. Marijana Zanoški Hren
Viša stručna savjetnica │Senior adviser

t: +385 1 5581663
e: marijana.zanoski-hren@mzoe.hr<mailto:marijana.zanoski-hren@mzoe.hr>

Radnička cesta 80, 10000 Zagreb
www.mzoe.gov.hr<http://www.mzoe.gov.hr/>


[cid:image002.jpg@01D5C4B0.4F6BCA10]<http://eu2020.hr/>




www.eu2020.hr<http://www.eu2020.hr/>


[cid:image001.png@01D4C76C.17A212C0]Razmislite o ispisu ove elektronske pošte, čuvajte prirodu.


IZJAVA O ODRICANJU OD ODGOVORNOSTI: Ova elektronička poruka može sadržavati osjetljive, povjerljive i/ili povlaštene informacije te je namijenjena isključivo naznačenom primatelju i/ili grupi primatelja. Ako ste je primili pogreškom, molimo Vas da o tome odmah obavijestite pošiljatelja te da izvornu poruku i sve njene priloge odmah, bez čitanja, trajno izbrišete. Neovlaštena uporaba, distribucija, otkrivanje, umnožavanje ili izmjena ove poruke je zabranjena. Sadržaj, stavovi i mišljenja izneseni u poruci su autorovi i ne predstavljaju nužno službeni stav Ministarstva zaštite okoliša i energetike. Budući da komunikacija putem interneta spada u otvoreni način razmjene informacija, Ministarstvo zaštite okoliša i energetike ne prihvaća nikakvu odgovornost za eventualnu štetu nastalu primitkom ove poruke i svih njezinih priloga.

DISCLAIMER: This email may contain sensitive, confidential and/or privileged information and is intended only for the recipient and/or group of recipients to which it is addressed. If you received this in error, please immediately notify the sender and permanently delete the original email and any attachments, without reading them. Any unauthorized use, dissemination, disclosure, copying of or change to this email is prohibited. The content, views and opinions expressed in this email are those of the sender only and do not necessarily represent the official views of the Ministry of Environment and Energy. As internet communication is an open form of information exchange, the Ministry of Environment and Energy excludes all liability for any loss or damage arising from the receipt of this message and any of its attachments.
